favicon: null
name: mikruhland
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0.1326165
  lightness: 1
  brandColors:
    - '#6C5F59'
    - '#FEFFFF'
    - '#8D908A'
    - '#433937'
    - '#BFC7CB'
  rhythmicContrast: 1
typography_spectrum: 0.2795699
layout_spectrum: 0.5842294
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
