favicon: null
name: mikruhland
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0.1326165
  lightness: 1
  brandColors:
    - '#000000'
    - '#FED502'
    - '#B79901'
    - '#FD0001'
    - '#D8C0B9'
  rhythmicContrast: 0
typography_spectrum: 0.7831541
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
layout_spectrum: 1
